/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cenarios;

import entidades.Usuarios;

/**
 *
 * @author Edson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Login l;
    Funcionario f;
    Campa c;
    Cemiterio cm;
    Familia fm;
    Malogrado m;
    Exumacao e;
    Telefone t;
    public Principal() {
        
        initComponents();
        f= new Funcionario();
        c= new Campa();
        fm= new Familia();
        cm = new Cemiterio();
        m = new Malogrado();
        e= new Exumacao();
        t = new Telefone();
        l = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBarOperario = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cCampa = new javax.swing.JMenuItem();
        cFuncionario = new javax.swing.JMenuItem();
        cFamilia = new javax.swing.JMenuItem();
        cCemiterio = new javax.swing.JMenuItem();
        cMalogrado = new javax.swing.JMenuItem();
        Contactos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Enterro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SG Cemiterio");

        jDesktopPanePrincipal.setPreferredSize(new java.awt.Dimension(500, 350));
        jDesktopPanePrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jDesktopPanePrincipalMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        cCampa.setText("Campa");
        cCampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCampaActionPerformed(evt);
            }
        });
        jMenu1.add(cCampa);

        cFuncionario.setText("Funcionario");
        cFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(cFuncionario);

        cFamilia.setText("Familia");
        cFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFamiliaActionPerformed(evt);
            }
        });
        jMenu1.add(cFamilia);

        cCemiterio.setText("Cemiterio");
        cCemiterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCemiterioActionPerformed(evt);
            }
        });
        jMenu1.add(cCemiterio);

        cMalogrado.setText("Malogrado");
        cMalogrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMalogradoActionPerformed(evt);
            }
        });
        jMenu1.add(cMalogrado);

        Contactos.setText("Contactos");
        Contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactosActionPerformed(evt);
            }
        });
        jMenu1.add(Contactos);

        jMenuBarOperario.add(jMenu1);

        jMenu2.setText("Operacoes");

        Enterro.setText("Exumacao");
        Enterro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterroActionPerformed(evt);
            }
        });
        jMenu2.add(Enterro);

        jMenuBarOperario.add(jMenu2);

        jMenu3.setText("Contactos");

        jMenuItem1.setText("jMenuItem1");
        jMenu3.add(jMenuItem1);

        jMenuBarOperario.add(jMenu3);

        setJMenuBar(jMenuBarOperario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFuncionarioActionPerformed


          jDesktopPanePrincipal.add(f);
          f.setSize(500,350);
          f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cFuncionarioActionPerformed

    private void cCampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCampaActionPerformed
        // TODO add your handling code here:
        jDesktopPanePrincipal.add(c);
        c.setSize(500,350);
        c.setVisible(true);
    }//GEN-LAST:event_cCampaActionPerformed

    private void cFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFamiliaActionPerformed
        // TODO add your handling code here:
        jDesktopPanePrincipal.add(fm);
        fm.setSize(500,350);
        fm.setVisible(true);
    }//GEN-LAST:event_cFamiliaActionPerformed

    private void cCemiterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCemiterioActionPerformed
        // TODOjDesktopPanePrincipal.add(c);
       jDesktopPanePrincipal.add(cm);
        cm.setSize(500,350);
        cm.setVisible(true);
    }//GEN-LAST:event_cCemiterioActionPerformed

    private void cMalogradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMalogradoActionPerformed
        // TODO add your handling code here:
        jDesktopPanePrincipal.add(m);
        m.setSize(500,350);
        m.setVisible(true);
    }//GEN-LAST:event_cMalogradoActionPerformed

    private void EnterroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterroActionPerformed
        // TODO add your handling code here:
        jDesktopPanePrincipal.add(e);
        e.setSize(500,350);
        e.setVisible(true);
    }//GEN-LAST:event_EnterroActionPerformed

    private void ContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactosActionPerformed
        // TODO add your handling code here:
        jDesktopPanePrincipal.add(t);
        t.setSize(500,350);
        t.setVisible(true);
    }//GEN-LAST:event_ContactosActionPerformed

    private void jDesktopPanePrincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPanePrincipalMouseMoved
        // TODO add your handling code here:
       /* jDesktopPanePrincipal.add(l);
        l.setSize(500,350);
        l.setVisible(true);
       */ 
        
    }//GEN-LAST:event_jDesktopPanePrincipalMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Contactos;
    private javax.swing.JMenuItem Enterro;
    private javax.swing.JMenuItem cCampa;
    private javax.swing.JMenuItem cCemiterio;
    private javax.swing.JMenuItem cFamilia;
    private javax.swing.JMenuItem cFuncionario;
    private javax.swing.JMenuItem cMalogrado;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarOperario;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
